// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIK4ekavLW3xbQeM0ph4oYLAklZNmaoY8',
    appId: '1:536153952717:web:460f87e4c9b5e44819f484',
    messagingSenderId: '536153952717',
    projectId: 'wya-app-d1efb',
    authDomain: 'wya-app-d1efb.firebaseapp.com',
    storageBucket: 'wya-app-d1efb.appspot.com',
    measurementId: 'G-M3Y1318W19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD8kBq4n9S_G0OE_GPJuKa46YFhLomhTA',
    appId: '1:536153952717:android:370367c711ff62cc19f484',
    messagingSenderId: '536153952717',
    projectId: 'wya-app-d1efb',
    storageBucket: 'wya-app-d1efb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ1RJYFrFN2uoBZc8nL2-nQPqOBGp-IvU',
    appId: '1:536153952717:ios:3525bb28d8d1cd1519f484',
    messagingSenderId: '536153952717',
    projectId: 'wya-app-d1efb',
    storageBucket: 'wya-app-d1efb.appspot.com',
    iosClientId: '536153952717-2d1ad23q7bcbhiq2khkr5umk5lthtgc5.apps.googleusercontent.com',
    iosBundleId: 'com.example.wyaFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ1RJYFrFN2uoBZc8nL2-nQPqOBGp-IvU',
    appId: '1:536153952717:ios:3525bb28d8d1cd1519f484',
    messagingSenderId: '536153952717',
    projectId: 'wya-app-d1efb',
    storageBucket: 'wya-app-d1efb.appspot.com',
    iosClientId: '536153952717-2d1ad23q7bcbhiq2khkr5umk5lthtgc5.apps.googleusercontent.com',
    iosBundleId: 'com.example.wyaFinal',
  );
}
